service: grade-ref-backup-lambda

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-west-1
  profile: graderef
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 's3:PutObject'
          Resource: 'arn:aws:s3:::graderef-prod-dumps/*'

functions:
  prod-db:
    handler: dist/handler.main
    events:
      - schedule: cron(0,30 * ? * * *)
    environment:
      DB_HOST: ${env:DB_HOST}
      DB_USERNAME: ${env:DB_USERNAME}
      DB_PASSWORD: ${env:DB_PASSWORD}
      DB_DATABASE: ${env:DB_DATABASE}
      AWS_BUCKET: ${env:AWS_BUCKET}
  dev-db:
    handler: dist/handler.main
    events:
      - schedule: cron(0,30 * ? * * *)
    environment:
      DB_HOST: ${env:DB_HOST_DEV}
      DB_USERNAME: ${env:DB_USERNAME_DEV}
      DB_PASSWORD: ${env:DB_PASSWORD_DEV}
      DB_DATABASE: ${env:DB_DATABASE_DEV}
      AWS_BUCKET: ${env:AWS_BUCKET_DEV}
